---
- name: Install the syzygyauthenticator from github
  git:
    repo: '{{ syzygyauthenticator_repo }}'
    dest: '{{ syzygyauthenticator_dir }}'
    version: '{{ syzygyauthenticator_version }}'

- name: Install the jhub_remote_user_authenticator
  pip:
    name: '{{ remote_user_authenticator }}'
    executable: pip3.6
  when:
    jupyterhub_authenticator == 'shib'

- name: Install the syzygyauthenticator
  pip:
    name: '{{ syzygyauthenticator_dir }}'
    executable: pip3.6
