---
- name: Manage landing page html repo
  include_role:
    name: '{{ jupyterhub_html_family }}'

- name: Manage dockerspawner
  include_role:
    name: dockerspawner
  when: jupyterhub_spawner in ['syzygysystemuserspawner', 'syzygyswiftsystemuserspawner']

- name: Manage Jupyterhub Docker Cull script
  include_role:
    name: jhub-docker-cull
  when: jupyterhub_spawner in ['syzygysystemuserspawner', 'syzygyswiftsystemuserspawner']

- name: Get Docker image for JupyterHub containers
  docker_image:
    name: '{{ jupyterhub_docker_container }}'
  when: jupyterhub_spawner in ['syzygysystemuserspawner', 'syzygyswiftsystemuserspawner']

- name: Manage syzygyauthenticator
  include_role:
    name: syzygyauthenticator

- name: Manage Shibboleth
  include_role:
    name: shibboleth-sp
  when: jupyterhub_authenticator == 'shib'

- name: Examine groups
  debug:
    msg: "Content of group_names is {{ group_names }}"

- name: Add a jupyter user to run things as
  user:
    name: "jupyter"

- name: Get the jupyter uidNumber
  getent:
    database: passwd
    key: "jupyter"
    split: ':'

- name: Collect the UserID for jupyter user
  set_fact:
    jupyterhub_user_uid: '{{ getent_passwd["jupyter"][1] }}'

- name: Install pycurl dependencies
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    update_cache: yes
  with_items:
    - { 'name': 'libcurl-devel', 'state': 'present' }

- name: Install pycurl
  pip:
    name: pycurl
    executable: pip3.6
  environment:
    PYCURL_SSL_LIBRARY: nss

- name: Install Jupyterhub
  pip:
    name: jupyterhub
    executable: pip3.6

- name: Install node packages
  yum:
    name: nodejs
    state: present

- name: Install configurable-http-proxy
  npm:
    name: configurable-http-proxy
    state: present
    global: yes

- name: Create JupyterHub Config Directory
  file:
    path: '{{ jupyterhub_srv_dir }}'
    state: directory
    mode: '0755'

- name: Add Jupyterhub Config
  template:
    src: jupyterhub_config_base.py.j2
    dest: "{{ jupyterhub_srv_dir }}/jupyterhub_config.py"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart JupyterHub

- name: Jupyterhub Service config
  template:
    src: jupyterhub-env.j2
    dest: /etc/sysconfig/jupyterhub
    mode: 0600
    owner: root
    group: root

- name: Jupyterhub Service definition
  template:
    src: jupyterhub.service.j2
    dest: /etc/systemd/system/jupyterhub.service
  notify:
    - Start JupyterHub

- name: Add jupyterhub port to to home zone (assume firewalld)
  firewalld:
    zone: "home"
    port: "{{ jupyterhub_api_port }}/tcp"
    immediate: yes
    state: enabled
    permanent: true
