---
## Updates all packages on a host
- name: Update Packages
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
      ignore_errors: true
      when: "not disable_package_updates | default(false)"
