---
# Tasks for base package installation (RedHat)
- name: Setup epel repo
  yum:
    name: "epel-release"
    state: present
    update_cache: yes
  tags: setup

- name: Install base packages
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    update_cache: yes
  tags: setup
  with_items: '{{ base_packages }}'

# Auto-security updates
- name: Ensure yum fully updated
  yum:
    name: yum
    state: latest
    update_cache: yes
  become: yes

- name: Install centos-yum-security dependencies
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    update_cache: yes
  with_items:
    - { name: 'mailx',  state: 'present' }
    - { name: 'yum-plugin-changelog',  state: 'present' }

- name: Install centos-package-cron from RPM
  yum:
    name: '{{ base_packages_centos_cron_rpm_url }}'
    state: 'present'

- name: Install centos-yum-security script
  get_url:
    src: '{{ base_packages_centos_yum_security_url }}'
    dest: '/usr/bin/centos-yum-security'
    checksum: 'sha256:{{ base_packages_centos_yum_security_sha256 }}'
    mode: 0750
    owner: root
    group: root

- name: Add cron job for centos-package-cron
  cron:
    name: "check for updates"
    minute: 30 
    hour: 12 
    user: root
    cron_file: centos-package-cron
    job: '/usr/bin/centos-yum-security &>/dev/null'

- name: Add a cron job for need-restarting
  cron:
    name: "Systemd services asking for a restart"
    minute: 40
    hour: 12
    weekday: 5
    cron_file
    job: '/usr/bin/needs-restarting -s'

- name: Add a cron job for systemd services needing a reboot
  template:
    src: needs-restarting.sh.j2
    dest: /etc/cron.daily/needs-restarting.sh
    mode: 0750
    owner: root
    group: root
