---
# Tasks for base package installation (RedHat)
- name: Setup epel repo
  yum:
    name: "epel-release"
    state: present
    update_cache: yes
  tags: setup

- name: Install base packages
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    update_cache: yes
  tags: setup
  with_items: '{{ base_packages }}'

# Auto-security updates
- name: Ensure yum fully updated
  yum:
    name: yum
    state: latest
    update_cache: yes
  become: yes

- name: Install centos-package-cron from RPM
  yum:
    name: '{{ base_packages_centos_cron_rpm_url }}'
    state: 'present'

- name: Add cron job for centos-package-cron
  cron:
    name: "check for updates"
    minute: 14
    hour: 5
    user: root
    cron_file: centos-package-cron
    job: '/usr/bin/centos-package-cron &>/dev/null'
