---
# This is shared betwen ssp and callysto-html
ssp_ver: 1.15.4
ssp_path: /var
ssp_prefix: simplesamlphp-
ssp_dir: "{{ ssp_path  }}/{{ ssp_prefix  }}{{ ssp_ver }}"

jupyterhub_srv_dir: '/srv/jupyterhub'
jupyterhub_api_port: '8081'

jupyterhub_shib_dir: '/opt/shib_authenticator'

jhub_docker_cull_run_s: 1800
jhub_docker_cull_cull_s: 10800

jupyterhub_docker_image: 'docker.io/callysto/pims-minimal'
jupyterhub_docker_container: 'docker.io/callysto/pims-minimal:latest'

jupyterhub_global_options:
  - conf_object: 'JupyterHub.admin_access'
    value: False
  - conf_object: 'JupyterHub.base_url'
    value: "'/jupyter'"
  - conf_object: 'JupyterHub.confirm_no_ssl'
    value: True
  - conf_object: 'JupyterHub.hub_ip'
    value: "'{{ ansible_docker0.ipv4.address }}'"
  - conf_object: 'JupyterHub.ip'
    value: "'127.0.0.1'"
  - conf_object: 'JupyterHub.services'
    value: |
        [
            {
                'name': 'cull-idle',
                'admin': True,
                'command': [
                    'python3',
                    '/opt/cull_idle_servers.py',
                    '--timeout={{ jhub_docker_cull_cull_s }}',
                    '--cull-every={{ jhub_docker_cull_run_s }}',
                ]
            }
        ]


jupyterhub_spawner: 'syzygysystemuserspawner'
jupyterhub_authenticator: 'pam'
