---
jupyterhub_spawners:
  syzygyswiftsystemuserspawner:
    name: 'syzygyauthenticator.swiftsystemuserspawner.SyzygySwiftSystemUserSpawner'
    options:
      - conf_object: 'DockerSpawner.use_internal_ip'
        value: True
      - conf_object: 'SystemUserSpawner.image'
        value: "'{{ jupyterhub_docker_container }}'"
      - conf_object: 'SystemUserSpawner.extra_host_config'
        value: "{'mem_limit': '2g', 'memswap_limit': '2g', 'cpu_period': 100000, 'cpu_quota': 100000 }"
      - conf_object: 'SystemUserSpawner.remove_containers'
        value: 'True'
      - conf_object: 'SystemUserSpawner.host_ip'
        value: "'0.0.0.0'"
      - conf_object: 'SystemUserSpawner.host_homedir_format_string'
        value: "'/tank/home/{username}'"
      - conf_object: 'SystemUserSpawner.openstack_auth_info'
        value: |
          {
            'OS_AUTH_URL': '{{ openstack_auth_url }}',
            'OS_USERNAME': '{{ openstack_username }}',
            'OS_PASSWORD': '{{ openstack_password }}',
            'OS_PROJECT_NAME': '{{ openstack_project_name }}',
            'OS_PROJECT_DOMAIN_NAME': '{{  openstack_project_domain_name }}',
            'OS_USER_DOMAIN_NAME': '{{  openstack_user_domain_name }}',
            'OS_REGION_NAME': '{{  openstack_region_name }}',
          }
