---
jupyterhub_authenticators:
  shib:
    name: 'syzygyauthenticator.shib.RemoteUserAuthenticator'
    options:
      - conf_object: 'SyzygyAuthenticator.user_id'
        value: '{{ jupyterhub_user_uid }}'
      - conf_object: 'SyzygyAuthenticator.homedir_string'
        value: "'/tank/home/USERNAME'"
      - conf_object: 'SyzygyAuthenticator.create_homedir_cmd'
        value: "['/opt/syzygyauthenticator/zfs-homedir.sh', 'USERNAME', 'jupyter']"
      - conf_object: 'SyzygyAuthenticator.create_system_users'
        value: 'False'
      - conf_object: 'SyzygyAuthenticator.create_user_homedir'
        value: 'True'
