---
jupyterhub_spawners:
  syzygysystemuserspawner:
    name: 'syzygyauthenticator.systemuserspawner.SyzygySystemUserSpawner'
    options:
      - conf_object: 'DockerSpawner.use_internal_ip'
        value: True
      - conf_object: 'SystemUserSpawner.image'
        value: "'{{ jupyterhub_docker_container }}'"
      - conf_object: 'SystemUserSpawner.extra_host_config'
        value: "{'mem_limit': '2g', 'memswap_limit': '2g', 'cpu_period': 100000, 'cpu_quota': 100000 }"
      - conf_object: 'SystemUserSpawner.remove_containers'
        value: 'True'
      - conf_object: 'SystemUserSpawner.host_ip'
        value: "'0.0.0.0'"
      - conf_object: 'SystemUserSpawner.host_homedir_format_string'
        value: "'/tank/home/{username}'"
