---
- name: Copy the SSL certificates
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - src: '{{ callysto_ssl_cert_dir }}/cert.pem'
      dest: '/etc/pki/tls/certs/cert.pem'
    - src: '{{ callysto_ssl_cert_dir }}/chain.pem'
      dest: '/etc/pki/tls/certs/chain.pem'
    - src: '{{ callysto_ssl_cert_dir }}/privkey.pem'
      dest: '/etc/pki/tls/private/privkey.pem'

- name: Ensure proper permissions on private key file
  file:
    path: '/etc/pki/tls/private/privkey.pem'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: Install HTML files
  git:
    repo: '{{ callysto_hub_landing_page_repo }}'
    version: "{{ callysto_landing_branch }}"
    dest: '{{ callysto_html_dir.src }}'
    ssh_opts: "-o StrictHostKeyChecking=no"
  notify:
    - Copy landing page templates
    - Update image assets

- name: Flush handlers
  meta: flush_handlers

- name: Grab html template from host
  run_once : true
  fetch:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    flat: yes
    fail_on_missing: yes
  with_items:
    - src: '{{ callysto_html_dir.src }}/index.html'
      dest: '/var/tmp/callysto-html-index.html'
    - src: '{{ callysto_html_dir.src }}/logout/index.html'
      dest: '/var/tmp/callysto-html-logout-index.html'

- name: Process html template and send results back to host
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - dest: '{{ callysto_html_dir.dest }}/index.html'
      src: '/var/tmp/callysto-html-index.html'
    - dest: '{{ callysto_html_dir.dest }}/logout/index.html'
      src: '/var/tmp/callysto-html-logout-index.html'

- name: Update DocumentRoot
  notify:
    - restart apache
  lineinfile:
    dest: '/etc/httpd/conf/httpd.conf'
    regexp: '^DocumentRoot'
    line: 'DocumentRoot "{{ callysto_html_dir.dest }}"'

- name: Add httpd config for jupyter service
  template:
    src: jupyter-http.conf.j2
    dest: /etc/httpd/conf.d/jupyter.conf
    mode: 0644
    owner: root
    group: root
  notify: restart apache
