---
- name: Copy ZFS yum repo
  copy:
    src: files/zfs.repo
    dest: /etc/yum.repos.d/zfs.repo

- name: Copy ZFS GPG key
  copy:
    src: files/RPM-GPG-KEY-zfsonlinux
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux

- name: Install zfs kernel module
  yum:
    name: zfs
    state: present
    update_cache: yes
  notify:
    - Modprobe zfs

- name: Ensure the ZFS kernel module is loaded
  modprobe:
    name: zfs

- name: Flush ZFS Handlers
  meta: flush_handlers

- name: Create tank zpool
  notify:
   - Start zfs
  command: /sbin/zpool create -f '{{ zfs_pool_name }}' '{{ zfs_vdev_config }}'
  args:
    creates: /tank
  when: zfs_vdev_config is defined

- name: Create ZFS home container
  command: /sbin/zfs create '{{ zfs_pool_name }}'/home
  args:
    creates: '/{{ zfs_pool_name }}/home'
  when: zfs_vdev_config is defined
