---
- name: Copy ZFS yum repo
  copy:
    src: files/zfs.repo
    dest: /etc/yum.repos.d/zfs.repo

- name: Copy ZFS GPG key
  copy:
    src: files/RPM-GPG-KEY-zfsonlinux
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux

- name: Install zfs kernel module
  yum:
    name: zfs
    state: present
    update_cache: yes
  notify:
    - Modprobe zfs

- name: Ensure the ZFS kernel module is loaded
  modprobe:
    name: zfs

- name: Flush ZFS Handlers
  meta: flush_handlers

- name: Create tank zpool
  notify:
   - Start zfs
  command: /sbin/zpool create -f tank mirror '{{ zfs_disk_1 }}' '{{ zfs_disk_2 }}'
  args:
    creates: /tank
  when: zfs_disk_1 is defined

- name: Create ZFS home container
  command: /sbin/zfs create tank/home
  args:
    creates: /tank/home
  when: zfs_disk_1 is defined
